using System.Collections.Generic;

namespace Library
{
    public static class Libraries
    {
        public static Dictionary<LibraryFile, string> LibraryList = new Dictionary<LibraryFile, string>
        {
            [LibraryFile.Interface1c] = $"{AppInfo.AppPath}Data/Interface1c.Zl",
            [LibraryFile.Interface] = $"{AppInfo.AppPath}Data/Interface.Zl",
            [LibraryFile.GameInter] = $"{AppInfo.AppPath}Data/GameInter.Zl",
            [LibraryFile.Equip] = $"{AppInfo.AppPath}Data/Equip.Zl",
            [LibraryFile.EquipEffect_UI] = $"{AppInfo.AppPath}Data/EquipEffect-UI.Zl",
            [LibraryFile.EquipEffect_Part] = $"{AppInfo.AppPath}Data/EquipEffect-Part.Zl",
            [LibraryFile.EquipEffect_Full] = $"{AppInfo.AppPath}Data/EquipEffect-Full.Zl",
            [LibraryFile.EquipEffect_FullEx1] = $"{AppInfo.AppPath}Data/EquipEffect-FullEx1.Zl",
            [LibraryFile.EquipEffect_FullEx2] = $"{AppInfo.AppPath}Data/EquipEffect-FullEx2.Zl",
            [LibraryFile.EquipEffect_FullEx3] = $"{AppInfo.AppPath}Data/EquipEffect-FullEx3.Zl",
            [LibraryFile.ProgUse] = $"{AppInfo.AppPath}Data/ProgUse.Zl",
            [LibraryFile.StoreItems] = $"{AppInfo.AppPath}Data/StoreItems.Zl",
            [LibraryFile.Inventory] = $"{AppInfo.AppPath}Data/Inventory.Zl",
            [LibraryFile.Ground] = $"{AppInfo.AppPath}Data/Ground.Zl",
            [LibraryFile.NPC] = $"{AppInfo.AppPath}Data/NPC.Zl",
            [LibraryFile.GameInter2] = $"{AppInfo.AppPath}Data/GameInter2.Zl",
            [LibraryFile.MiniMap] = $"{AppInfo.AppPath}Data/MiniMap.Zl",
            [LibraryFile.MiniMap2] = $"{AppInfo.AppPath}Data/MiniMap2.Zl",

            [LibraryFile.CastleFlag] = $"{AppInfo.AppPath}Data/Flag.Zl",

            [LibraryFile.MiniMapIcon] = $"{AppInfo.AppPath}Data/MiniMapIcon.Zl",

            [LibraryFile.Background] = $"{AppInfo.AppPath}Data/Background.Zl",

            [LibraryFile.MagicIcon] = $"{AppInfo.AppPath}Data/MIcon.Zl",
            [LibraryFile.CBIcon] = $"{AppInfo.AppPath}Data/CBIcons.Zl",
            [LibraryFile.QuestIcon] = $"{AppInfo.AppPath}Data/QuestIcons.Zl",

            [LibraryFile.MiniGames] = $"{AppInfo.AppPath}Data/MiniGames.Zl",

            [LibraryFile.NPCImage] = $"{AppInfo.AppPath}Data/NPCface.Zl",
            [LibraryFile.MonImage] = $"{AppInfo.AppPath}data/monster/monImg.Zl",

            [LibraryFile.PEquipB1] = $"{AppInfo.AppPath}Data/PEquipB1.Zl",
            [LibraryFile.PEquipH1] = $"{AppInfo.AppPath}Data/PEquipH1.Zl",

            [LibraryFile.M_Hum] = $"{AppInfo.AppPath}data/player/m-Hum.Zl",
            [LibraryFile.M_HumEx1] = $"{AppInfo.AppPath}data/player/m-HumEx1.Zl",
            [LibraryFile.M_HumEx2] = $"{AppInfo.AppPath}data/player/m-HumEx2.Zl",
            [LibraryFile.M_HumEx3] = $"{AppInfo.AppPath}data/player/m-HumEx3.Zl",
            [LibraryFile.M_HumEx4] = $"{AppInfo.AppPath}data/player/m-HumEx4.Zl",
            [LibraryFile.M_HumEx10] = $"{AppInfo.AppPath}data/player/m-HumEx10.Zl",
            [LibraryFile.M_HumEx11] = $"{AppInfo.AppPath}data/player/m-HumEx11.Zl",
            [LibraryFile.M_HumEx12] = $"{AppInfo.AppPath}data/player/m-HumEx12.Zl",
            [LibraryFile.M_HumEx13] = $"{AppInfo.AppPath}data/player/m-HumEx13.Zl",

            [LibraryFile.WM_Hum] = $"{AppInfo.AppPath}data/player/wm-Hum.Zl",
            [LibraryFile.WM_HumEx1] = $"{AppInfo.AppPath}data/player/wm-HumEx1.Zl",
            [LibraryFile.WM_HumEx2] = $"{AppInfo.AppPath}data/player/wm-HumEx2.Zl",
            [LibraryFile.WM_HumEx3] = $"{AppInfo.AppPath}data/player/wm-HumEx3.Zl",
            [LibraryFile.WM_HumEx4] = $"{AppInfo.AppPath}data/player/wm-HumEx4.Zl",
            [LibraryFile.WM_HumEx10] = $"{AppInfo.AppPath}data/player/wm-HumEx10.Zl",
            [LibraryFile.WM_HumEx11] = $"{AppInfo.AppPath}data/player/wm-HumEx11.Zl",
            [LibraryFile.WM_HumEx12] = $"{AppInfo.AppPath}data/player/wm-HumEx12.Zl",
            [LibraryFile.WM_HumEx13] = $"{AppInfo.AppPath}data/player/wm-HumEx13.Zl",

            [LibraryFile.M_Hair] = $"{AppInfo.AppPath}data/player/m-Hair.Zl",
            [LibraryFile.WM_Hair] = $"{AppInfo.AppPath}data/player/wm-Hair.Zl",

            [LibraryFile.M_HumA] = $"{AppInfo.AppPath}data/player/m-HumA.Zl",
            [LibraryFile.M_HumAEx1] = $"{AppInfo.AppPath}data/player/m-HumAEx1.Zl",
            [LibraryFile.M_HumAEx2] = $"{AppInfo.AppPath}data/player/m-HumAEx2.Zl",
            [LibraryFile.M_HumAEx3] = $"{AppInfo.AppPath}data/player/m-HumAEx3.Zl",

            [LibraryFile.WM_HumA] = $"{AppInfo.AppPath}data/player/wm-HumA.Zl",
            [LibraryFile.WM_HumAEx1] = $"{AppInfo.AppPath}data/player/wm-HumAEx1.Zl",
            [LibraryFile.WM_HumAEx2] = $"{AppInfo.AppPath}data/player/wm-HumAEx2.Zl",
            [LibraryFile.WM_HumAEx3] = $"{AppInfo.AppPath}data/player/wm-HumAEx3.Zl",

            [LibraryFile.M_HairA] = $"{AppInfo.AppPath}data/player/m-HairA.Zl",
            [LibraryFile.WM_HairA] = $"{AppInfo.AppPath}data/player/wm-HairA.Zl",

            [LibraryFile.M_Costume] = $"{AppInfo.AppPath}data/player/m-Costume.Zl",
            [LibraryFile.M_CostumeA] = $"{AppInfo.AppPath}data/player/m-CostumeA.Zl",
            [LibraryFile.M_CostumeEx1] = $"{AppInfo.AppPath}data/player/m-CostumeEx1.Zl",

            [LibraryFile.WM_Costume] = $"{AppInfo.AppPath}data/player/wm-Costume.Zl",
            [LibraryFile.WM_CostumeA] = $"{AppInfo.AppPath}data/player/wm-CostumeA.Zl",
            [LibraryFile.WM_CostumeEx1] = $"{AppInfo.AppPath}data/player/wm-CostumeEx1.Zl",

            [LibraryFile.Horse] = $"{AppInfo.AppPath}data/player/horse.Zl",
            [LibraryFile.HorseIron] = $"{AppInfo.AppPath}data/player/horse_Iron.Zl",
            [LibraryFile.HorseSilver] = $"{AppInfo.AppPath}data/player/horse_Silver.Zl",
            [LibraryFile.HorseGold] = $"{AppInfo.AppPath}data/player/horse_Golden.Zl",
            [LibraryFile.HorseBlue] = $"{AppInfo.AppPath}data/player/horse_Blue.Zl",
            [LibraryFile.HorseDark] = $"{AppInfo.AppPath}data/player/horse_Dark.Zl",
            [LibraryFile.HorseDarkEffect] = $"{AppInfo.AppPath}data/player/horse_DarkEffect.Zl",
            [LibraryFile.HorseRoyal] = $"{AppInfo.AppPath}data/player/horse_Royal.Zl",
            [LibraryFile.HorseRoyalEffect] = $"{AppInfo.AppPath}data/player/horse_RoyalEffect.Zl",
            [LibraryFile.HorseBlueDragon] = $"{AppInfo.AppPath}data/player/horse_BlueDragon.Zl",
            [LibraryFile.HorseBlueDragonEffect] = $"{AppInfo.AppPath}data/player/horse_BlueDragonEffect.Zl",

            [LibraryFile.M_Shield1] = $"{AppInfo.AppPath}data/player/m-Shield1.Zl",
            [LibraryFile.M_Shield2] = $"{AppInfo.AppPath}data/player/m-Shield2.Zl",
            [LibraryFile.WM_Shield1] = $"{AppInfo.AppPath}data/player/wm-Shield1.Zl",
            [LibraryFile.WM_Shield2] = $"{AppInfo.AppPath}data/player/wm-Shield2.Zl",

            [LibraryFile.M_Weapon1] = $"{AppInfo.AppPath}data/player/m-Weapon1.Zl",
            [LibraryFile.M_Weapon2] = $"{AppInfo.AppPath}data/player/m-Weapon2.Zl",
            [LibraryFile.M_Weapon3] = $"{AppInfo.AppPath}data/player/m-Weapon3.Zl",
            [LibraryFile.M_Weapon4] = $"{AppInfo.AppPath}data/player/m-Weapon4.Zl",
            [LibraryFile.M_Weapon5] = $"{AppInfo.AppPath}data/player/m-Weapon5.Zl",
            [LibraryFile.M_Weapon6] = $"{AppInfo.AppPath}data/player/m-Weapon6.Zl",
            [LibraryFile.M_Weapon7] = $"{AppInfo.AppPath}data/player/m-Weapon7.Zl",
            [LibraryFile.M_Weapon10] = $"{AppInfo.AppPath}data/player/m-Weapon10.Zl",
            [LibraryFile.M_Weapon11] = $"{AppInfo.AppPath}data/player/m-Weapon11.Zl",
            [LibraryFile.M_Weapon12] = $"{AppInfo.AppPath}data/player/m-Weapon12.Zl",
            [LibraryFile.M_Weapon13] = $"{AppInfo.AppPath}data/player/m-Weapon13.Zl",
            [LibraryFile.M_Weapon14] = $"{AppInfo.AppPath}data/player/m-Weapon14.Zl",
            [LibraryFile.M_Weapon15] = $"{AppInfo.AppPath}data/player/m-Weapon15.Zl",
            [LibraryFile.M_Weapon16] = $"{AppInfo.AppPath}data/player/m-Weapon16.Zl",

            [LibraryFile.WM_Weapon1] = $"{AppInfo.AppPath}data/player/wm-Weapon1.Zl",
            [LibraryFile.WM_Weapon2] = $"{AppInfo.AppPath}data/player/wm-Weapon2.Zl",
            [LibraryFile.WM_Weapon3] = $"{AppInfo.AppPath}data/player/wm-Weapon3.Zl",
            [LibraryFile.WM_Weapon4] = $"{AppInfo.AppPath}data/player/wm-Weapon4.Zl",
            [LibraryFile.WM_Weapon5] = $"{AppInfo.AppPath}data/player/wm-Weapon5.Zl",
            [LibraryFile.WM_Weapon6] = $"{AppInfo.AppPath}data/player/wm-Weapon6.Zl",
            [LibraryFile.WM_Weapon7] = $"{AppInfo.AppPath}data/player/wm-Weapon7.Zl",
            [LibraryFile.WM_Weapon10] = $"{AppInfo.AppPath}data/player/wm-Weapon10.Zl",
            [LibraryFile.WM_Weapon11] = $"{AppInfo.AppPath}data/player/wm-Weapon11.Zl",
            [LibraryFile.WM_Weapon12] = $"{AppInfo.AppPath}data/player/wm-Weapon12.Zl",
            [LibraryFile.WM_Weapon13] = $"{AppInfo.AppPath}data/player/wm-Weapon13.Zl",
            [LibraryFile.WM_Weapon14] = $"{AppInfo.AppPath}data/player/wm-Weapon14.Zl",
            [LibraryFile.WM_Weapon15] = $"{AppInfo.AppPath}data/player/wm-Weapon15.Zl",
            [LibraryFile.WM_Weapon16] = $"{AppInfo.AppPath}data/player/wm-Weapon16.Zl",

            [LibraryFile.M_WeaponADL1] = $"{AppInfo.AppPath}data/player/m-WeaponADL1.Zl",
            [LibraryFile.M_WeaponADL2] = $"{AppInfo.AppPath}data/player/m-WeaponADL2.Zl",
            [LibraryFile.M_WeaponADL6] = $"{AppInfo.AppPath}data/player/m-WeaponADL6.Zl",
            [LibraryFile.M_WeaponADR1] = $"{AppInfo.AppPath}data/player/m-WeaponADR1.Zl",
            [LibraryFile.M_WeaponADR2] = $"{AppInfo.AppPath}data/player/m-WeaponADR2.Zl",
            [LibraryFile.M_WeaponADR6] = $"{AppInfo.AppPath}data/player/m-WeaponADR6.Zl",

            [LibraryFile.M_WeaponAOH1] = $"{AppInfo.AppPath}data/player/m-WeaponAOH1.Zl",
            [LibraryFile.M_WeaponAOH2] = $"{AppInfo.AppPath}data/player/m-WeaponAOH2.Zl",
            [LibraryFile.M_WeaponAOH3] = $"{AppInfo.AppPath}data/player/m-WeaponAOH3.Zl",
            [LibraryFile.M_WeaponAOH4] = $"{AppInfo.AppPath}data/player/m-WeaponAOH4.Zl",
            [LibraryFile.M_WeaponAOH5] = $"{AppInfo.AppPath}data/player/m-WeaponAOH5.Zl",
            [LibraryFile.M_WeaponAOH6] = $"{AppInfo.AppPath}data/player/m-WeaponAOH6.Zl",

            [LibraryFile.WM_WeaponADL1] = $"{AppInfo.AppPath}data/player/wm-WeaponADL1.Zl",
            [LibraryFile.WM_WeaponADL2] = $"{AppInfo.AppPath}data/player/wm-WeaponADL2.Zl",
            [LibraryFile.WM_WeaponADL6] = $"{AppInfo.AppPath}data/player/wm-WeaponADL6.Zl",
            [LibraryFile.WM_WeaponADR1] = $"{AppInfo.AppPath}data/player/wm-WeaponADR1.Zl",
            [LibraryFile.WM_WeaponADR2] = $"{AppInfo.AppPath}data/player/wm-WeaponADR2.Zl",
            [LibraryFile.WM_WeaponADR6] = $"{AppInfo.AppPath}data/player/wm-WeaponADR6.Zl",

            [LibraryFile.WM_WeaponAOH1] = $"{AppInfo.AppPath}data/player/wm-WeaponAOH1.Zl",
            [LibraryFile.WM_WeaponAOH2] = $"{AppInfo.AppPath}data/player/wm-WeaponAOH2.Zl",
            [LibraryFile.WM_WeaponAOH3] = $"{AppInfo.AppPath}data/player/wm-WeaponAOH3.Zl",
            [LibraryFile.WM_WeaponAOH4] = $"{AppInfo.AppPath}data/player/wm-WeaponAOH4.Zl",
            [LibraryFile.WM_WeaponAOH5] = $"{AppInfo.AppPath}data/player/wm-WeaponAOH5.Zl",
            [LibraryFile.WM_WeaponAOH6] = $"{AppInfo.AppPath}data/player/wm-WeaponAOH6.Zl",

            [LibraryFile.M_Helmet1] = $"{AppInfo.AppPath}data/player/m-Helmet1.Zl",
            [LibraryFile.M_Helmet2] = $"{AppInfo.AppPath}data/player/m-Helmet2.Zl",
            [LibraryFile.M_Helmet3] = $"{AppInfo.AppPath}data/player/m-Helmet3.Zl",
            [LibraryFile.M_Helmet4] = $"{AppInfo.AppPath}data/player/m-Helmet4.Zl",
            [LibraryFile.M_Helmet5] = $"{AppInfo.AppPath}data/player/m-Helmet5.Zl",

            [LibraryFile.M_Helmet11] = $"{AppInfo.AppPath}data/player/m-Helmet11.Zl",
            [LibraryFile.M_Helmet12] = $"{AppInfo.AppPath}data/player/m-Helmet12.Zl",
            [LibraryFile.M_Helmet13] = $"{AppInfo.AppPath}data/player/m-Helmet13.Zl",
            [LibraryFile.M_Helmet14] = $"{AppInfo.AppPath}data/player/m-Helmet14.Zl",

            [LibraryFile.WM_Helmet1] = $"{AppInfo.AppPath}data/player/wm-Helmet1.Zl",
            [LibraryFile.WM_Helmet2] = $"{AppInfo.AppPath}data/player/wm-Helmet2.Zl",
            [LibraryFile.WM_Helmet3] = $"{AppInfo.AppPath}data/player/wm-Helmet3.Zl",
            [LibraryFile.WM_Helmet4] = $"{AppInfo.AppPath}data/player/wm-Helmet4.Zl",
            [LibraryFile.WM_Helmet5] = $"{AppInfo.AppPath}data/player/wm-Helmet5.Zl",

            [LibraryFile.WM_Helmet11] = $"{AppInfo.AppPath}data/player/wm-Helmet11.Zl",
            [LibraryFile.WM_Helmet12] = $"{AppInfo.AppPath}data/player/wm-Helmet12.Zl",
            [LibraryFile.WM_Helmet13] = $"{AppInfo.AppPath}data/player/wm-Helmet13.Zl",
            [LibraryFile.WM_Helmet14] = $"{AppInfo.AppPath}data/player/wm-Helmet14.Zl",

            [LibraryFile.M_HelmetA1] = $"{AppInfo.AppPath}data/player/m-HelmetA1.Zl",
            [LibraryFile.M_HelmetA2] = $"{AppInfo.AppPath}data/player/m-HelmetA2.Zl",
            [LibraryFile.M_HelmetA3] = $"{AppInfo.AppPath}data/player/m-HelmetA3.Zl",
            [LibraryFile.M_HelmetA4] = $"{AppInfo.AppPath}data/player/m-HelmetA4.Zl",

            [LibraryFile.WM_HelmetA1] = $"{AppInfo.AppPath}data/player/wm-HelmetA1.Zl",
            [LibraryFile.WM_HelmetA2] = $"{AppInfo.AppPath}data/player/wm-HelmetA2.Zl",
            [LibraryFile.WM_HelmetA3] = $"{AppInfo.AppPath}data/player/wm-HelmetA3.Zl",
            [LibraryFile.WM_HelmetA4] = $"{AppInfo.AppPath}data/player/wm-HelmetA4.Zl",

            [LibraryFile.MonMagic] = $"{AppInfo.AppPath}data/monster/monMagic.Zl", //
            [LibraryFile.MonMagicEx] = $"{AppInfo.AppPath}data/monster/monMagicEx.Zl", //
            [LibraryFile.MonMagicEx2] = $"{AppInfo.AppPath}data/monster/monMagicEx2.Zl", //
            [LibraryFile.MonMagicEx3] = $"{AppInfo.AppPath}data/monster/monMagicEx3.Zl", //
            [LibraryFile.MonMagicEx4] = $"{AppInfo.AppPath}data/monster/monMagicEx4.Zl", //
            [LibraryFile.MonMagicEx5] = $"{AppInfo.AppPath}data/monster/monMagicEx5.Zl", //
            [LibraryFile.MonMagicEx6] = $"{AppInfo.AppPath}data/monster/monMagicEx6.Zl", //
            [LibraryFile.MonMagicEx7] = $"{AppInfo.AppPath}data/monster/monMagicEx7.Zl", //
            [LibraryFile.MonMagicEx8] = $"{AppInfo.AppPath}data/monster/monMagicEx8.Zl", //
            [LibraryFile.MonMagicEx9] = $"{AppInfo.AppPath}data/monster/monMagicEx9.Zl", //
            [LibraryFile.MonMagicEx19] = $"{AppInfo.AppPath}data/monster/monMagicEx19.Zl", //
            [LibraryFile.MonMagicEx20] = $"{AppInfo.AppPath}data/monster/monMagicEx20.Zl", //
            [LibraryFile.MonMagicEx21] = $"{AppInfo.AppPath}data/monster/monMagicEx21.Zl", //
            [LibraryFile.MonMagicEx22] = $"{AppInfo.AppPath}data/monster/monMagicEx22.Zl", //
            [LibraryFile.MonMagicEx23] = $"{AppInfo.AppPath}data/monster/monMagicEx23.Zl", //
            [LibraryFile.MonMagicEx26] = $"{AppInfo.AppPath}data/monster/monMagicEx26.Zl", //

            [LibraryFile.Mon_1] = $"{AppInfo.AppPath}data/monster/mon-1.Zl",
            [LibraryFile.Mon_2] = $"{AppInfo.AppPath}data/monster/mon-2.Zl",
            [LibraryFile.Mon_3] = $"{AppInfo.AppPath}data/monster/mon-3.Zl",
            [LibraryFile.Mon_4] = $"{AppInfo.AppPath}data/monster/mon-4.Zl",
            [LibraryFile.Mon_5] = $"{AppInfo.AppPath}data/monster/mon-5.Zl",
            [LibraryFile.Mon_6] = $"{AppInfo.AppPath}data/monster/mon-6.Zl",
            [LibraryFile.Mon_7] = $"{AppInfo.AppPath}data/monster/mon-7.Zl",
            [LibraryFile.Mon_8] = $"{AppInfo.AppPath}data/monster/mon-8.Zl",
            [LibraryFile.Mon_9] = $"{AppInfo.AppPath}data/monster/mon-9.Zl",
            [LibraryFile.Mon_10] = $"{AppInfo.AppPath}data/monster/mon-10.Zl",

            [LibraryFile.Mon_11] = $"{AppInfo.AppPath}data/monster/mon-11.Zl",
            [LibraryFile.Mon_12] = $"{AppInfo.AppPath}data/monster/mon-12.Zl",
            [LibraryFile.Mon_13] = $"{AppInfo.AppPath}data/monster/mon-13.Zl",
            [LibraryFile.Mon_14] = $"{AppInfo.AppPath}data/monster/mon-14.Zl",
            [LibraryFile.Mon_15] = $"{AppInfo.AppPath}data/monster/mon-15.Zl",
            [LibraryFile.Mon_16] = $"{AppInfo.AppPath}data/monster/mon-16.Zl",
            [LibraryFile.Mon_17] = $"{AppInfo.AppPath}data/monster/mon-17.Zl",
            [LibraryFile.Mon_18] = $"{AppInfo.AppPath}data/monster/mon-18.Zl",
            [LibraryFile.Mon_19] = $"{AppInfo.AppPath}data/monster/mon-19.Zl",
            [LibraryFile.Mon_20] = $"{AppInfo.AppPath}data/monster/mon-20.Zl",

            [LibraryFile.Mon_21] = $"{AppInfo.AppPath}data/monster/mon-21.Zl",
            [LibraryFile.Mon_22] = $"{AppInfo.AppPath}data/monster/mon-22.Zl",
            [LibraryFile.Mon_23] = $"{AppInfo.AppPath}data/monster/mon-23.Zl",
            [LibraryFile.Mon_24] = $"{AppInfo.AppPath}data/monster/mon-24.Zl",
            [LibraryFile.Mon_25] = $"{AppInfo.AppPath}data/monster/mon-25.Zl",
            [LibraryFile.Mon_26] = $"{AppInfo.AppPath}data/monster/mon-26.Zl",
            [LibraryFile.Mon_27] = $"{AppInfo.AppPath}data/monster/mon-27.Zl",
            [LibraryFile.Mon_28] = $"{AppInfo.AppPath}data/monster/mon-28.Zl",
            [LibraryFile.Mon_29] = $"{AppInfo.AppPath}data/monster/mon-29.Zl",
            [LibraryFile.Mon_30] = $"{AppInfo.AppPath}data/monster/mon-30.Zl",

            [LibraryFile.Mon_31] = $"{AppInfo.AppPath}data/monster/mon-31.Zl",
            [LibraryFile.Mon_32] = $"{AppInfo.AppPath}data/monster/mon-32.Zl",
            [LibraryFile.Mon_33] = $"{AppInfo.AppPath}data/monster/mon-33.Zl",
            [LibraryFile.Mon_34] = $"{AppInfo.AppPath}data/monster/mon-34.Zl",
            [LibraryFile.Mon_35] = $"{AppInfo.AppPath}data/monster/mon-35.Zl",
            [LibraryFile.Mon_36] = $"{AppInfo.AppPath}data/monster/mon-36.Zl",
            [LibraryFile.Mon_37] = $"{AppInfo.AppPath}data/monster/mon-37.Zl",
            [LibraryFile.Mon_38] = $"{AppInfo.AppPath}data/monster/mon-38.Zl",
            [LibraryFile.Mon_39] = $"{AppInfo.AppPath}data/monster/mon-39.Zl",
            [LibraryFile.Mon_40] = $"{AppInfo.AppPath}data/monster/mon-40.Zl",

            [LibraryFile.Mon_41] = $"{AppInfo.AppPath}data/monster/mon-41.Zl",
            [LibraryFile.Mon_42] = $"{AppInfo.AppPath}data/monster/mon-42.Zl",
            [LibraryFile.Mon_43] = $"{AppInfo.AppPath}data/monster/mon-43.Zl",
            [LibraryFile.Mon_44] = $"{AppInfo.AppPath}data/monster/mon-44.Zl",
            [LibraryFile.Mon_45] = $"{AppInfo.AppPath}data/monster/mon-45.Zl",
            [LibraryFile.Mon_46] = $"{AppInfo.AppPath}data/monster/mon-46.Zl",
            [LibraryFile.Mon_47] = $"{AppInfo.AppPath}data/monster/mon-47.Zl",
            [LibraryFile.Mon_48] = $"{AppInfo.AppPath}data/monster/mon-48.Zl",
            [LibraryFile.Mon_49] = $"{AppInfo.AppPath}data/monster/mon-49.Zl",
            [LibraryFile.Mon_50] = $"{AppInfo.AppPath}data/monster/mon-50.Zl",

            [LibraryFile.Mon_51] = $"{AppInfo.AppPath}data/monster/mon-51.Zl",
            [LibraryFile.Mon_52] = $"{AppInfo.AppPath}data/monster/mon-52.Zl",
            [LibraryFile.Mon_53] = $"{AppInfo.AppPath}data/monster/mon-53.Zl",
            [LibraryFile.Mon_54] = $"{AppInfo.AppPath}data/monster/mon-54.Zl",
            [LibraryFile.Mon_55] = $"{AppInfo.AppPath}data/monster/mon-55.Zl",
            [LibraryFile.Mon_56] = $"{AppInfo.AppPath}data/monster/mon-56.Zl",

            [LibraryFile.Magic] = $"{AppInfo.AppPath}Data/Magic.Zl",
            [LibraryFile.MagicEx] = $"{AppInfo.AppPath}Data/MagicEx.Zl",
            [LibraryFile.MagicEx2] = $"{AppInfo.AppPath}Data/MagicEx2.Zl",
            [LibraryFile.MagicEx3] = $"{AppInfo.AppPath}Data/MagicEx3.Zl",
            [LibraryFile.MagicEx4] = $"{AppInfo.AppPath}Data/MagicEx4.Zl",
            [LibraryFile.MagicEx5] = $"{AppInfo.AppPath}Data/MagicEx5.Zl",
            [LibraryFile.MagicEx6] = $"{AppInfo.AppPath}Data/MagicEx6.Zl",
            [LibraryFile.MagicEx7] = $"{AppInfo.AppPath}Data/MagicEx7.Zl",
            [LibraryFile.MagicEx8] = $"{AppInfo.AppPath}Data/MagicEx8.Zl",
            [LibraryFile.MagicEx9] = $"{AppInfo.AppPath}Data/MagicEx9.Zl",
            [LibraryFile.MagicEx10] = $"{AppInfo.AppPath}Data/MagicEx10.Zl",
            [LibraryFile.MagicEx11] = $"{AppInfo.AppPath}Data/MagicEx11.Zl",

            [LibraryFile.Animationsc] = $"{AppInfo.AppPath}map/map_data/Animationsc.Zl",
            [LibraryFile.Cliffsc] = $"{AppInfo.AppPath}map/map_data/Cliffsc.Zl",
            [LibraryFile.Dungeonsc] = $"{AppInfo.AppPath}map/map_data/Dungeonsc.Zl",
            [LibraryFile.Furnituresc] = $"{AppInfo.AppPath}map/map_data/Furnituresc.Zl",
            [LibraryFile.Housesc] = $"{AppInfo.AppPath}map/map_data/Housesc.Zl",
            [LibraryFile.Innersc] = $"{AppInfo.AppPath}map/map_data/Innersc.Zl",
            [LibraryFile.Object1c] = $"{AppInfo.AppPath}map/map_data/Object1c.Zl",
            [LibraryFile.Object2c] = $"{AppInfo.AppPath}map/map_data/Object2c.Zl",
            [LibraryFile.SmObjectsc] = $"{AppInfo.AppPath}map/map_data/SmObjectsc.Zl",
            [LibraryFile.SmTilesc] = $"{AppInfo.AppPath}map/map_data/SmTilesc.Zl",
            [LibraryFile.Tiles5c] = $"{AppInfo.AppPath}map/map_data/Tiles5c.Zl",
            [LibraryFile.Tiles30c] = $"{AppInfo.AppPath}map/map_data/Tiles30c.Zl",
            [LibraryFile.Tilesc] = $"{AppInfo.AppPath}map/map_data/Tilesc.Zl",
            [LibraryFile.Wallsc] = $"{AppInfo.AppPath}map/map_data/Wallsc.Zl",

            [LibraryFile.Forest_Animationsc] = $"{AppInfo.AppPath}map/map_data/Forest/Animationsc.Zl",
            [LibraryFile.Forest_Cliffsc] = $"{AppInfo.AppPath}map/map_data/Forest/Cliffsc.Zl",
            [LibraryFile.Forest_Dungeonsc] = $"{AppInfo.AppPath}map/map_data/Forest/Dungeonsc.Zl",
            [LibraryFile.Forest_Furnituresc] = $"{AppInfo.AppPath}map/map_data/Forest/Furnituresc.Zl",
            [LibraryFile.Forest_Housesc] = $"{AppInfo.AppPath}map/map_data/Forest/Housesc.Zl",
            [LibraryFile.Forest_Innersc] = $"{AppInfo.AppPath}map/map_data/Forest/Innersc.Zl",
            [LibraryFile.Forest_SmObjectsc] = $"{AppInfo.AppPath}map/map_data/Forest/SmObjectsc.Zl",
            [LibraryFile.Forest_SmTilesc] = $"{AppInfo.AppPath}map/map_data/Forest/SmTilesc.Zl",
            [LibraryFile.Forest_Tiles5c] = $"{AppInfo.AppPath}map/map_data/Forest/Tiles5c.Zl",
            [LibraryFile.Forest_Tiles30c] = $"{AppInfo.AppPath}map/map_data/Forest/Tiles30c.Zl",
            [LibraryFile.Forest_Tilesc] = $"{AppInfo.AppPath}map/map_data/Forest/Tilesc.Zl",
            [LibraryFile.Forest_Wallsc] = $"{AppInfo.AppPath}map/map_data/Forest/Wallsc.Zl",

            [LibraryFile.Sand_Animationsc] = $"{AppInfo.AppPath}map/map_data/Sand/Animationsc.Zl",
            [LibraryFile.Sand_Cliffsc] = $"{AppInfo.AppPath}map/map_data/Sand/Cliffsc.Zl",
            [LibraryFile.Sand_Dungeonsc] = $"{AppInfo.AppPath}map/map_data/Sand/Dungeonsc.Zl",
            [LibraryFile.Sand_Furnituresc] = $"{AppInfo.AppPath}map/map_data/Sand/Furnituresc.Zl",
            [LibraryFile.Sand_Housesc] = $"{AppInfo.AppPath}map/map_data/Sand/Housesc.Zl",
            [LibraryFile.Sand_Innersc] = $"{AppInfo.AppPath}map/map_data/Sand/Innersc.Zl",
            [LibraryFile.Sand_SmObjectsc] = $"{AppInfo.AppPath}map/map_data/Sand/SmObjectsc.Zl",
            [LibraryFile.Sand_SmTilesc] = $"{AppInfo.AppPath}map/map_data/Sand/SmTilesc.Zl",
            [LibraryFile.Sand_Tiles5c] = $"{AppInfo.AppPath}map/map_data/Sand/Tiles5c.Zl",
            [LibraryFile.Sand_Tiles30c] = $"{AppInfo.AppPath}map/map_data/Sand/Tiles30c.Zl",
            [LibraryFile.Sand_Tilesc] = $"{AppInfo.AppPath}map/map_data/Sand/Tilesc.Zl",
            [LibraryFile.Sand_Wallsc] = $"{AppInfo.AppPath}map/map_data/Sand/Wallsc.Zl",

            [LibraryFile.Snow_Animationsc] = $"{AppInfo.AppPath}map/map_data/Snow/Animationsc.Zl",
            [LibraryFile.Snow_Cliffsc] = $"{AppInfo.AppPath}map/map_data/Snow/Cliffsc.Zl",
            [LibraryFile.Snow_Dungeonsc] = $"{AppInfo.AppPath}map/map_data/Snow/Dungeonsc.Zl",
            [LibraryFile.Snow_Furnituresc] = $"{AppInfo.AppPath}map/map_data/Snow/Furnituresc.Zl",
            [LibraryFile.Snow_Housesc] = $"{AppInfo.AppPath}map/map_data/Snow/Housesc.Zl",
            [LibraryFile.Snow_Innersc] = $"{AppInfo.AppPath}map/map_data/Snow/Innersc.Zl",
            [LibraryFile.Snow_SmObjectsc] = $"{AppInfo.AppPath}map/map_data/Snow/SmObjectsc.Zl",
            [LibraryFile.Snow_SmTilesc] = $"{AppInfo.AppPath}map/map_data/Snow/SmTilesc.Zl",
            [LibraryFile.Snow_Tiles5c] = $"{AppInfo.AppPath}map/map_data/Snow/Tiles5c.Zl",
            [LibraryFile.Snow_Tiles30c] = $"{AppInfo.AppPath}map/map_data/Snow/Tiles30c.Zl",
            [LibraryFile.Snow_Tilesc] = $"{AppInfo.AppPath}map/map_data/Snow/Tilesc.Zl",
            [LibraryFile.Snow_Wallsc] = $"{AppInfo.AppPath}map/map_data/Snow/Wallsc.Zl",

            [LibraryFile.Wood_Animationsc] = $"{AppInfo.AppPath}map/map_data/Wood/Animationsc.Zl",
            [LibraryFile.Wood_Cliffsc] = $"{AppInfo.AppPath}map/map_data/Wood/Cliffsc.Zl",
            [LibraryFile.Wood_Dungeonsc] = $"{AppInfo.AppPath}map/map_data/Wood/Dungeonsc.Zl",
            [LibraryFile.Wood_Furnituresc] = $"{AppInfo.AppPath}map/map_data/Wood/Furnituresc.Zl",
            [LibraryFile.Wood_Housesc] = $"{AppInfo.AppPath}map/map_data/Wood/Housesc.Zl",
            [LibraryFile.Wood_Innersc] = $"{AppInfo.AppPath}map/map_data/Wood/Innersc.Zl",
            [LibraryFile.Wood_SmObjectsc] = $"{AppInfo.AppPath}map/map_data/Wood/SmObjectsc.Zl",
            [LibraryFile.Wood_SmTilesc] = $"{AppInfo.AppPath}map/map_data/Wood/SmTilesc.Zl",
            [LibraryFile.Wood_Tiles5c] = $"{AppInfo.AppPath}map/map_data/Wood/Tiles5c.Zl",
            [LibraryFile.Wood_Tiles30c] = $"{AppInfo.AppPath}map/map_data/Wood/Tiles30c.Zl",
            [LibraryFile.Wood_Tilesc] = $"{AppInfo.AppPath}map/map_data/Wood/Tilesc.Zl",
            [LibraryFile.Wood_Wallsc] = $"{AppInfo.AppPath}map/map_data/Wood/Wallsc.Zl",
        };

        public static Dictionary<int, LibraryFile> KROrder = new Dictionary<int, LibraryFile>
        {
            [0] = LibraryFile.Tilesc,
            [1] = LibraryFile.Tiles30c,
            [2] = LibraryFile.Tiles5c,
            [3] = LibraryFile.SmTilesc,
            [4] = LibraryFile.Housesc,
            [5] = LibraryFile.Cliffsc,
            [6] = LibraryFile.Dungeonsc,
            [7] = LibraryFile.Innersc,
            [8] = LibraryFile.Furnituresc,
            [9] = LibraryFile.Wallsc,
            [10] = LibraryFile.SmObjectsc,
            [11] = LibraryFile.Animationsc,
            [12] = LibraryFile.Object1c,
            [13] = LibraryFile.Object2c,

            [15] = LibraryFile.Wood_Tilesc,
            [16] = LibraryFile.Wood_Tiles30c,
            [17] = LibraryFile.Wood_Tiles5c,
            [18] = LibraryFile.Wood_SmTilesc,
            [19] = LibraryFile.Wood_Housesc,
            [20] = LibraryFile.Wood_Cliffsc,
            [21] = LibraryFile.Wood_Dungeonsc,
            [22] = LibraryFile.Wood_Innersc,
            [23] = LibraryFile.Wood_Furnituresc,
            [24] = LibraryFile.Wood_Wallsc,
            [25] = LibraryFile.Wood_SmObjectsc,
            [26] = LibraryFile.Wood_Animationsc,

            [30] = LibraryFile.Sand_Tilesc,
            [31] = LibraryFile.Sand_Tiles30c,
            [32] = LibraryFile.Sand_Tiles5c,
            [33] = LibraryFile.Sand_SmTilesc,
            [34] = LibraryFile.Sand_Housesc,
            [35] = LibraryFile.Sand_Cliffsc,
            [36] = LibraryFile.Sand_Dungeonsc,
            [37] = LibraryFile.Sand_Innersc,
            [38] = LibraryFile.Sand_Furnituresc,
            [39] = LibraryFile.Sand_Wallsc,
            [40] = LibraryFile.Sand_SmObjectsc,
            [41] = LibraryFile.Sand_Animationsc,

            [45] = LibraryFile.Snow_Tilesc,
            [46] = LibraryFile.Snow_Tiles30c,
            [47] = LibraryFile.Snow_Tiles5c,
            [48] = LibraryFile.Snow_SmTilesc,
            [49] = LibraryFile.Snow_Housesc,
            [50] = LibraryFile.Snow_Cliffsc,
            [51] = LibraryFile.Snow_Dungeonsc,
            [52] = LibraryFile.Snow_Innersc,
            [53] = LibraryFile.Snow_Furnituresc,
            [54] = LibraryFile.Snow_Wallsc,
            [55] = LibraryFile.Snow_SmObjectsc,
            [56] = LibraryFile.Snow_Animationsc,

            [60] = LibraryFile.Forest_Tilesc,
            [61] = LibraryFile.Forest_Tiles30c,
            [62] = LibraryFile.Forest_Tiles5c,
            [63] = LibraryFile.Forest_SmTilesc,
            [64] = LibraryFile.Forest_Housesc,
            [65] = LibraryFile.Forest_Cliffsc,
            [66] = LibraryFile.Forest_Dungeonsc,
            [67] = LibraryFile.Forest_Innersc,
            [68] = LibraryFile.Forest_Furnituresc,
            [69] = LibraryFile.Forest_Wallsc,
            [70] = LibraryFile.Forest_SmObjectsc,
            [71] = LibraryFile.Forest_Animationsc,
        };
    }

    public enum LibraryFile
    {
        None,

        Interface1c,
        Interface,
        GameInter,
        GameInter2,
        Equip,
        EquipEffect_UI,
        EquipEffect_Part,
        EquipEffect_Full,
        EquipEffect_FullEx1,
        EquipEffect_FullEx2,
        EquipEffect_FullEx3,
        ProgUse,
        StoreItems,
        Inventory,
        Ground,
        NPC,
        MiniMap,
        MiniMap2,
        MagicIcon,
        CBIcon,
        QuestIcon,
        MiniGames,
        CastleFlag,
        MiniMapIcon,
        Background,

        NPCImage,
        MonImage,

        PEquipB1,
        PEquipH1,

        M_Hum,
        M_HumEx1,
        M_HumEx2,
        M_HumEx3,
        M_HumEx4,
        M_HumEx10,
        M_HumEx11,
        M_HumEx12,
        M_HumEx13,
        M_Hair,

        WM_Hum,
        WM_HumEx1,
        WM_HumEx2,
        WM_HumEx3,
        WM_HumEx4,
        WM_HumEx10,
        WM_HumEx11,
        WM_HumEx12,
        WM_HumEx13,
        WM_Hair,

        M_HumA,
        M_HumAEx1,
        M_HumAEx2,
        M_HumAEx3,
        M_HairA,

        WM_HumA,
        WM_HumAEx1,
        WM_HumAEx2,
        WM_HumAEx3,
        WM_HairA,

        M_Costume,
        M_CostumeA,
        M_CostumeEx1,

        WM_Costume,
        WM_CostumeA,
        WM_CostumeEx1,

        Horse,
        HorseS,

        HorseIron,
        HorseSilver,
        HorseGold,
        HorseBlue,
        HorseDark,
        HorseDarkEffect,
        HorseRoyal,
        HorseRoyalEffect,
        HorseBlueDragon,
        HorseBlueDragonEffect,

        M_Weapon1,
        M_Weapon2,
        M_Weapon3,
        M_Weapon4,
        M_Weapon5,
        M_Weapon6,
        M_Weapon7,
        M_Weapon10,
        M_Weapon11,
        M_Weapon12,
        M_Weapon13,
        M_Weapon14,
        M_Weapon15,
        M_Weapon16,

        WM_Weapon1,
        WM_Weapon2,
        WM_Weapon3,
        WM_Weapon4,
        WM_Weapon5,
        WM_Weapon6,
        WM_Weapon7,
        WM_Weapon10,
        WM_Weapon11,
        WM_Weapon12,
        WM_Weapon13,
        WM_Weapon14,
        WM_Weapon15,
        WM_Weapon16,

        M_WeaponADL1,
        M_WeaponADL2,
        M_WeaponADL6,
        M_WeaponADR1,
        M_WeaponADR2,
        M_WeaponADR6,

        M_WeaponAOH1,
        M_WeaponAOH2,
        M_WeaponAOH3,
        M_WeaponAOH4,
        M_WeaponAOH5,
        M_WeaponAOH6,

        WM_WeaponADL1,
        WM_WeaponADL2,
        WM_WeaponADL6,
        WM_WeaponADR1,
        WM_WeaponADR2,
        WM_WeaponADR6,

        WM_WeaponAOH1,
        WM_WeaponAOH2,
        WM_WeaponAOH3,
        WM_WeaponAOH4,
        WM_WeaponAOH5,
        WM_WeaponAOH6,

        M_Shield1,
        M_Shield2,

        WM_Shield1,
        WM_Shield2,

        M_Helmet1,
        M_Helmet2,
        M_Helmet3,
        M_Helmet4,
        M_Helmet5,

        M_Helmet11,
        M_Helmet12,
        M_Helmet13,
        M_Helmet14,

        WM_Helmet1,
        WM_Helmet2,
        WM_Helmet3,
        WM_Helmet4,
        WM_Helmet5,

        WM_Helmet11,
        WM_Helmet12,
        WM_Helmet13,
        WM_Helmet14,

        M_HelmetA1,
        M_HelmetA2,
        M_HelmetA3,
        M_HelmetA4,

        WM_HelmetA1,
        WM_HelmetA2,
        WM_HelmetA3,
        WM_HelmetA4,

        MonMagic,
        MonMagicEx,
        MonMagicEx2,
        MonMagicEx3,
        MonMagicEx4,
        MonMagicEx5,
        MonMagicEx6,
        MonMagicEx7,
        MonMagicEx8,
        MonMagicEx9,
        MonMagicEx19,
        MonMagicEx20,
        MonMagicEx21,
        MonMagicEx22,
        MonMagicEx23,
        MonMagicEx26,

        Mon_1,
        Mon_2,
        Mon_3,
        Mon_4,
        Mon_5,
        Mon_6,
        Mon_7,
        Mon_8,
        Mon_9,
        Mon_10,

        Mon_11,
        Mon_12,
        Mon_13,
        Mon_14,
        Mon_15,
        Mon_16,
        Mon_17,
        Mon_18,
        Mon_19,
        Mon_20,

        Mon_21,
        Mon_22,
        Mon_23,
        Mon_24,
        Mon_25,
        Mon_26,
        Mon_27,
        Mon_28,
        Mon_29,
        Mon_30,

        Mon_31,
        Mon_32,
        Mon_33,
        Mon_34,
        Mon_35,
        Mon_36,
        Mon_37,
        Mon_38,
        Mon_39,
        Mon_40,

        Mon_41,
        Mon_42,
        Mon_43,
        Mon_44,
        Mon_45,
        Mon_46,
        Mon_47,
        Mon_48,
        Mon_49,
        Mon_50,

        Mon_51,
        Mon_52,
        Mon_53,
        Mon_54,
        Mon_55,
        Mon_56,

        Magic,
        MagicEx,
        MagicEx2,
        MagicEx3,
        MagicEx4,
        MagicEx5,
        MagicEx6,
        MagicEx7,
        MagicEx8,
        MagicEx9,
        MagicEx10,
        MagicEx11,

        Animationsc,
        Cliffsc,
        Dungeonsc,
        Furnituresc,
        Housesc,
        Innersc,
        Object1c,
        Object2c,
        SmObjectsc,
        SmTilesc,
        Tiles5c,
        Tiles30c,
        Tilesc,
        Wallsc,

        Forest_Animationsc,
        Forest_Cliffsc,
        Forest_Dungeonsc,
        Forest_Furnituresc,
        Forest_Housesc,
        Forest_Innersc,
        Forest_SmObjectsc,
        Forest_SmTilesc,
        Forest_Tiles5c,
        Forest_Tiles30c,
        Forest_Tilesc,
        Forest_Wallsc,

        Sand_Animationsc,
        Sand_Cliffsc,
        Sand_Dungeonsc,
        Sand_Furnituresc,
        Sand_Housesc,
        Sand_Innersc,
        Sand_SmObjectsc,
        Sand_SmTilesc,
        Sand_Tiles5c,
        Sand_Tiles30c,
        Sand_Tilesc,
        Sand_Wallsc,

        Snow_Animationsc,
        Snow_Cliffsc,
        Snow_Dungeonsc,
        Snow_Furnituresc,
        Snow_Housesc,
        Snow_Innersc,
        Snow_SmObjectsc,
        Snow_SmTilesc,
        Snow_Tiles5c,
        Snow_Tiles30c,
        Snow_Tilesc,
        Snow_Wallsc,

        Wood_Animationsc,
        Wood_Cliffsc,
        Wood_Dungeonsc,
        Wood_Furnituresc,
        Wood_Housesc,
        Wood_Innersc,
        Wood_SmObjectsc,
        Wood_SmTilesc,
        Wood_Tiles5c,
        Wood_Tiles30c,
        Wood_Tilesc,
        Wood_Wallsc,
    }
}